/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import {GLTF} from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder016: THREE.Mesh;
    Cylinder016_1: THREE.Mesh;
    Cylinder016_2: THREE.Mesh;
  };
  materials: {
    ["Red.025"]: THREE.MeshStandardMaterial;
    ["White.025"]: THREE.MeshStandardMaterial;
    ["BrownDark.018"]: THREE.MeshStandardMaterial;
  };
};

export default function TargetModel(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(
    "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/target-stand/model.gltf",
  ) as GLTFResult;
  return (
    /* eslint-disable @typescript-eslint/ban-ts-comment */
    // @ts-ignore
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Cylinder016.geometry}
          material={materials["Red.025"]}
        />
        <mesh
          geometry={nodes.Cylinder016_1.geometry}
          material={materials["White.025"]}
        />
        <mesh
          geometry={nodes.Cylinder016_2.geometry}
          material={materials["BrownDark.018"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/target-stand/model.gltf",
);
